# This file is the entry point to configure your own HTTP routes.
# Files in the routes/ subdirectory configure the routes for your dependencies.

index:
    path: /
    defaults: { _controller: 'App\Controller\ArticleController::homepage' }

show:
    path: /news/{slug}
    defaults: { _controller: 'App\Controller\ArticleController::show' }

article_toggle_heart:
    path: /news/{slug}/heart
    defaults: { _controller: 'App\Controller\ArticleController::toggleArticleHeart' }
    methods: POST

article_new:
    path: /admin/article/new
    defaults: { _controller: 'App\Controller\ArticleAdminController::new' }